In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# import the dataset

dataset = pd.read_csv('Churn_Modelling.csv')
dataset.head(3)

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1

In [3]:
# check the null values
dataset.isnull().sum()

RowNumber          0
CustomerId         0
Surname            0
CreditScore        0
Geography          0
Gender             0
Age                0
Tenure             0
Balance            0
NumOfProducts      0
HasCrCard          0
IsActiveMember     0
EstimatedSalary    0
Exited             0
dtype: int64

In [4]:
# remove the unused features(columns)
dataset = dataset.drop(columns=['RowNumber', 'CustomerId', 'Surname', 'Geography', 'Gender'], axis=1)
dataset.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,42,2,0.00,1,1,1,101348.88,1
1,608,41,1,83807.86,1,0,1,112542.58,0
2,502,42,8,159660.80,3,1,0,113931.57,1

In [5]:
# input and output features

input_data = dataset.iloc[:, :-1]
output_data = dataset.iloc[:, -1]

In [6]:
# scale the input data

from sklearn.preprocessing import StandardScaler

ss = StandardScaler()

In [7]:
input_data = pd.DataFrame(ss.fit_transform(input_data), columns=input_data.columns)
input_data.head(3)

,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,-0.326221,0.293517,-1.041760,-1.225848,-0.911583,0.646092,0.970243,0.021886
1,-0.440036,0.198164,-1.387538,0.117350,-0.911583,-1.547768,0.970243,0.216534
2,-1.536794,0.293517,1.032908,1.333053,2.527057,0.646092,-1.030670,0.240687

In [8]:
# train test split the data

from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(input_data, output_data, test_size=0.2, random_state=42)

In [9]:
import tensorflow as tf
from keras.layers import Dense, BatchNormalization, Dropout
from keras.models import Sequential
from keras.regularizers import L2
from keras.callbacks import EarlyStopping

from sklearn.metrics import accuracy_score

In [10]:
ann = Sequential()

# ANN (Nural Networks)

In [23]:
# create the hidden layers, taking the 6 layers because input_data.shape has 8 features so we take less then 8
ann.add(Dense(units=6, input_dim=8, activation='relu', kernel_regularizer=L2(l2=0.01)))
ann.add(BatchNormalization())
ann.add(Dropout(0.2))  # dropout layer
ann.add(Dense(units=5, activation='relu', kernel_regularizer=L2(l2=0.01)))  # you could use regularization here too
ann.add(BatchNormalization())
ann.add(Dropout(0.2))  # dropout layer
ann.add(Dense(units=4, activation='relu'))  # you could use regularization here too
ann.add(BatchNormalization())
ann.add(Dropout(0.2))  # dropout layer
ann.add(Dense(units=3, activation='relu', kernel_regularizer=L2(l2=0.01)))  # you could use regularization here too
ann.add(BatchNormalization())
ann.add(Dropout(0.2))  # dropout layer
ann.add(Dense(units=2, activation='relu'))  # you could use regularization here too
ann.add(BatchNormalization())
ann.add(Dropout(0.2))  # dropout layer
ann.add(Dense(units=1, activation='sigmoid'))  # output layer

d:\anaconda3\envs\tf_310\lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [24]:
# compile the model
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [38]:

ann.fit(x_train, y_train, batch_size=100, epochs=50, validation_data=(x_test, y_test), callbacks= EarlyStopping())

Epoch 1/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7983 - loss: 0.5024 - val_accuracy: 0.8035 - val_loss: 0.4854
Epoch 2/50
80/80 ━━━━━━━━━━━━━━━━━━━━ 1s 13ms/step - accuracy: 0.7979 - loss: 0.5022 - val_accuracy: 0.8035 - val_loss: 0.4981

In [39]:
# check the accuracy of the model

accuracy_score(y_train, ann.predict(x_train) > 0.5), accuracy_score(y_test, ann.predict(x_test) > 0.5)

250/250 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

(0.7945, 0.8035)

In [ ]:
(0.82325, 0.829)