In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [5]:
# load the dataset

dataset = pd.read_csv('grocery_item_transactions.csv')
dataset.head(3)

   item1 item2   item3   item4  item5 item6  item7
0  Chips  Coke    Eggs  Diaper  Bread   NaN    NaN
1  Bread  Coke     NaN     NaN    NaN   NaN    NaN
2   Eggs  Milk  Butter    Coke    NaN   NaN    NaN

In [7]:
# now create a new dataset (list of list) that only contains items not NaN

market = []

for i in range(0, dataset.shape[0]):
    cust = []
    for j in dataset.columns:
        if type(dataset[j][i]) == str:
            cust.append(dataset[j][i])
    market.append(cust)

In [ ]:
# now get the most buy items

import collections

In [12]:
items = []
for i in market:
    for j in i:
        items.append(j)

collections.Counter(items)

Counter({'Beer': 524,
         'Chips': 506,
         'Butter': 497,
         'Milk': 493,
         'Coke': 492,
         'Eggs': 491,
         'Bread': 478,
         'Diaper': 476})

In [13]:
# now we need to figure out the association

from mlxtend.preprocessing.transactionencoder import TransactionEncoder

In [ ]:

tr = TransactionEncoder()
tr.fit(market)

TransactionEncoder()

In [15]:
tr.transform(market)

array([[False,  True, False, ...,  True,  True, False],
       [False,  True, False, ..., False, False, False],
       [False, False,  True, ..., False,  True,  True],
       ...,
       [False, False,  True, ...,  True,  True, False],
       [False, False,  True, ..., False, False, False],
       [False,  True,  True, ..., False,  True,  True]])

In [17]:
df = pd.DataFrame(tr.transform(market), columns = tr.columns_)

In [18]:
# now use Apriori Association

from mlxtend.frequent_patterns import apriori

In [21]:
apriori(df, min_support=0.05, use_colnames=True, max_len=3).sort_values(by=["support"])

    support                 itemsets
60    0.102    (Butter, Bread, Eggs)
66    0.104    (Diaper, Bread, Coke)
68    0.109      (Bread, Coke, Milk)
59    0.110  (Diaper, Butter, Bread)
69    0.110    (Diaper, Bread, Eggs)
..      ...                      ...
4     0.492                   (Coke)
7     0.493                   (Milk)
2     0.497                 (Butter)
3     0.506                  (Chips)
0     0.524                   (Beer)

[92 rows x 2 columns]

In [27]:
# now try to remove the max_length to check if we get any other association

pd.set_option('display.max_rows', None)
apriori(df, min_support=0.05, use_colnames=True).sort_values(by=["support"])

     support                        itemsets
128    0.050    (Butter, Bread, Eggs, Chips)
140    0.051     (Diaper, Bread, Coke, Eggs)
132    0.051   (Diaper, Butter, Bread, Eggs)
103    0.052     (Diaper, Bread, Beer, Eggs)
130    0.052   (Diaper, Butter, Bread, Coke)
133    0.052   (Diaper, Butter, Bread, Milk)
141    0.052     (Diaper, Bread, Coke, Milk)
144    0.052   (Diaper, Butter, Coke, Chips)
146    0.052     (Butter, Milk, Coke, Chips)
134    0.052    (Diaper, Bread, Coke, Chips)
151    0.052    (Diaper, Butter, Milk, Coke)
147    0.053   (Diaper, Butter, Eggs, Chips)
149    0.053     (Butter, Milk, Eggs, Chips)
127    0.053  (Diaper, Butter, Bread, Chips)
142    0.053       (Bread, Coke, Milk, Eggs)
107    0.054   (Diaper, Butter, Beer, Chips)
131    0.054     (Butter, Bread, Coke, Eggs)
126    0.055    (Butter, Bread, Coke, Chips)
105    0.055       (Bread, Milk, Beer, Eggs)
148    0.055   (Diaper, Butter, Milk, Chips)
125    0.056      (Diaper, Milk, Beer, Eggs)
123    0.056      (Diaper, Milk, Coke, Beer)
102    0.056       (Bread, Coke, Milk, Beer)
143    0.056     (Diaper, Bread, Milk, Eggs)
152    0.057      (Butter, Milk, Coke, Eggs)
153    0.057    (Diaper, Butter, Milk, Eggs)
157    0.057     (Diaper, Milk, Eggs, Chips)
137    0.058    (Diaper, Bread, Eggs, Chips)
114    0.058    (Diaper, Butter, Milk, Beer)
94     0.058   (Diaper, Butter, Bread, Beer)
95     0.058     (Butter, Bread, Beer, Eggs)
145    0.058     (Butter, Coke, Eggs, Chips)
104    0.058     (Diaper, Bread, Milk, Beer)
135    0.058      (Bread, Coke, Eggs, Chips)
110    0.059    (Diaper, Butter, Coke, Beer)
158    0.059      (Diaper, Milk, Coke, Eggs)
154    0.059     (Diaper, Coke, Eggs, Chips)
155    0.059     (Diaper, Milk, Coke, Chips)
139    0.060      (Bread, Milk, Eggs, Chips)
129    0.061    (Butter, Bread, Milk, Chips)
99     0.062      (Bread, Eggs, Beer, Chips)
96     0.062     (Butter, Bread, Milk, Beer)
136    0.062      (Bread, Coke, Milk, Chips)
115    0.062      (Butter, Milk, Beer, Eggs)
156    0.062       (Milk, Coke, Eggs, Chips)
98     0.062    (Diaper, Bread, Beer, Chips)
113    0.062    (Diaper, Butter, Beer, Eggs)
116    0.063     (Diaper, Coke, Beer, Chips)
150    0.063    (Diaper, Butter, Coke, Eggs)
120    0.063     (Diaper, Milk, Beer, Chips)
112    0.063      (Butter, Milk, Coke, Beer)
93     0.064     (Butter, Bread, Coke, Beer)
106    0.064     (Butter, Coke, Beer, Chips)
97     0.065      (Bread, Coke, Beer, Chips)
109    0.066     (Butter, Milk, Beer, Chips)
138    0.066    (Diaper, Bread, Milk, Chips)
119    0.066     (Diaper, Eggs, Beer, Chips)
122    0.066      (Diaper, Coke, Beer, Eggs)
108    0.067     (Butter, Eggs, Beer, Chips)
101    0.070       (Bread, Coke, Beer, Eggs)
124    0.072        (Milk, Coke, Beer, Eggs)
92     0.072    (Butter, Bread, Beer, Chips)
121    0.072       (Milk, Eggs, Beer, Chips)
118    0.073       (Milk, Coke, Beer, Chips)
100    0.077      (Bread, Milk, Beer, Chips)
117    0.079       (Coke, Eggs, Beer, Chips)
111    0.084      (Butter, Coke, Beer, Eggs)
60     0.102           (Butter, Bread, Eggs)
66     0.104           (Diaper, Bread, Coke)
68     0.109             (Bread, Coke, Milk)
69     0.110           (Diaper, Bread, Eggs)
59     0.110         (Diaper, Butter, Bread)
61     0.110           (Butter, Bread, Milk)
71     0.111             (Bread, Milk, Eggs)
58     0.111           (Butter, Bread, Coke)
39     0.113           (Diaper, Bread, Beer)
78     0.114            (Butter, Milk, Coke)
89     0.114            (Diaper, Milk, Coke)
70     0.115           (Diaper, Bread, Milk)
73     0.115         (Diaper, Butter, Chips)
76     0.115          (Diaper, Butter, Coke)
72     0.116           (Butter, Coke, Chips)
81     0.116            (Butter, Milk, Eggs)
82     0.116           (Diaper, Coke, Chips)
91     0.117            (Diaper, Milk, Eggs)
44     0.118          (Diaper, Butter, Beer)
51     0.118            (Diaper, Coke, Beer)
74     0.118           (Butter, Eggs, Chips)
88     0.118            (Diaper, Coke, Eggs)
79     0.119          (Diaper, Butter, Eggs)
80     0.119          (Diaper, Butter, Milk)
55     0.119            (Diaper, Milk, Beer)
85     0.120           (Diaper, Eggs, Chips)
67     0.120             (Bread, Coke, Eggs)
62     0.120            (Bread, Coke, Chips)
40     0.121             (Bread, Beer, Eggs)
64     0.121            (Bread, Eggs, Chips)
90     0.123              (Milk, Coke, Eggs)
63     0.123          (Diaper, Bread, Chips)
86     0.124           (Diaper, Milk, Chips)
87     0.124             (Milk, Eggs, Chips)
75     0.125           (Butter, Milk, Chips)
48     0.125           (Diaper, Beer, Chips)
84     0.127             (Milk, Coke, Chips)
38     0.127             (Bread, Coke, Beer)
54     0.127            (Diaper, Beer, Eggs)
57     0.128          (Butter, Bread, Chips)
77     0.128            (Butter, Coke, Eggs)
83     0.129             (Coke, Eggs, Chips)
41     0.129             (Bread, Milk, Beer)
42     0.131           (Butter, Beer, Chips)
36     0.131           (Butter, Bread, Beer)
56     0.132              (Milk, Beer, Eggs)
65     0.135            (Bread, Milk, Chips)
46     0.135            (Butter, Milk, Beer)
43     0.137            (Butter, Coke, Beer)
53     0.138              (Milk, Coke, Beer)
37     0.141            (Bread, Beer, Chips)
49     0.141             (Eggs, Beer, Chips)
47     0.141             (Coke, Beer, Chips)
50     0.142             (Milk, Beer, Chips)
45     0.143            (Butter, Beer, Eggs)
52     0.155              (Coke, Beer, Eggs)
18     0.227                 (Diaper, Bread)
15     0.230                 (Butter, Bread)
17     0.230                   (Bread, Coke)
23     0.230                (Diaper, Butter)
34     0.232                  (Diaper, Milk)
20     0.233                   (Bread, Milk)
30     0.234                  (Diaper, Coke)
19     0.234                   (Bread, Eggs)
33     0.236                  (Diaper, Eggs)
32     0.238                    (Milk, Coke)
12     0.240                  (Diaper, Beer)
35     0.241                    (Milk, Eggs)
22     0.241                  (Butter, Coke)
25     0.243                  (Butter, Milk)
27     0.243                 (Diaper, Chips)
24     0.243                  (Butter, Eggs)
28     0.244                   (Eggs, Chips)
26     0.246                   (Coke, Chips)
8      0.247                   (Bread, Beer)
31     0.251                    (Coke, Eggs)
21     0.255                 (Butter, Chips)
29     0.260                   (Milk, Chips)
16     0.260                  (Bread, Chips)
10     0.262                   (Beer, Chips)
9      0.269                  (Butter, Beer)
11     0.270                    (Coke, Beer)
13     0.271                    (Beer, Eggs)
14     0.275                    (Milk, Beer)
5      0.476                        (Diaper)
1      0.478                         (Bread)
6      0.491                          (Eggs)
4      0.492                          (Coke)
7      0.493                          (Milk)
2      0.497                        (Butter)
3      0.506                         (Chips)
0      0.524                          (Beer)

## Now you could see the item associations